### PR TITLE
abs

### LINKED ISSUE #15510: abs

### PR DESCRIPTION
**Pull request by codewithmayor**
Close #15510

### CODE REVIEW

**Comment by codewithmayor** [comment]
@nassimberrada Kindly review.

**Comment by codewithmayor** [comment]
Hi @nassimberrada . I have resolved the conflicts. Thanks for your time. Kindly note 2 tests are now failing whereas all tests passed before the merge. I made no file changes. What could be the issue?

**Comment by codewithmayor** [comment]
Hey @nassimberrada. This is the error message : "Check failure on line 17 in .github/workflows/test-ivy-experimental-nn.yml
GitHub Actions
/ .github/workflows/test-ivy-experimental-nn.yml
Invalid workflow file
You have an error in your yaml syntax on line 17"

I made no changes to this .yml file.

**Comment by codewithmayor** [comment]
Thanks Nassim!

**Comment by sachelsout** [comment]
image

Hello @codewithmayor , @nassimberrada . I was going through the code and came across a little mistake in the test_paddle_tensor.py . On line 257, shouldn't the function name be **'test_paddle_instance_abs'** instead of **'test_torch_instance_abs'** ?

**Comment by codewithmayor** [comment]
Hi @sachelsout, yes. I noticed that too (I don't remember making that mistake on my end). @nassimberrada I actually corrected it before the PR got merged but I guess it was merged before my changes reflected. You can check out my comment addressing this issue above from 2 weeks ago ([amended test function name]) or rather check out the below link: 
https://github.com/unifyai/ivy/pull/15644/commits/9c5a0cbb4959616a34e82b213c67fb5687570344

Thanks.

**Comment by sachelsout** [comment]
> **I actually corrected it before the PR got merged but I guess it was merged before my changes reflected.**

Yes, this might be the reason !

**Pull request merged**
