### PR TITLE
add torch frontend masked_scatter and masked_scatter_

### PR DESCRIPTION
**Pull request by Daniel4078**
# PR Description

## Related Issue

Closes #

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by Daniel4078** [comment]
@Sam-Armstrong Do you know why while the helper function I wrote generates input tensors of the same size (that follows the broadcastable requirement shown here https://pytorch.org/docs/stable/generated/torch.Tensor.masked_scatter_.html#torch.Tensor.masked_scatter_), the test still sometime fail with error of unable to broadcast between two arrays. I examine the logs and it seems like while torch masked scatter only require the source tensor to have enough element to account for all True entry in the mask tensor, other functions I used to implement it somehow requires the mask to have shape broadcastable to the source. What should I do?

**Comment by Sam-Armstrong** [comment]
@Daniel4078 I've fixed the implementation for `masked_scatter` so it passes the test (aside paddle backend). Please could you implement the fix for `masked_scatter_`, add a test for `masked_scatter_`, and remove the changes you made to `index_put`? Then we'll be ready to merge. Thanks! 😊

**Comment by Daniel4078** [comment]
@Sam-Armstrong I have done the changes you asked for, now only the paddle backend tests fail probabily due to someone forgot to pass the dtype parameter when converting to tensor in the implementaiton of put_along_axis in paddle backend. Thank you!

**Review by Sam-Armstrong — APPROVED** [review]
lgtm! thanks @Daniel4078 😁

**Pull request merged**
