### PR TITLE
Adam update function reformatting

### PR DESCRIPTION
**Pull request by dhakalaashish**
https://github.com/unifyai/ivy/issues/9175

### CODE REVIEW

**Comment by nathzi1505** [comment]
@dhakalaashish It seems there are some lint checks failing. Can you review and check those please?
Also, for reference please free to consult : https://lets-unify.ai/ivy/deep_dive.html

**Comment by dhakalaashish** [comment]
I have changed a few things in this latest commit. 
Now, it says that some tests are still unsuccessful, but there aren't any more lint errors. 
Please guide me.

**Comment by dhakalaashish** [comment]
Hi @nathzi1505 please check my PR. I have corrected the lint error.
Thank you.

**Comment by nathzi1505** [comment]
Thanks @dhakalaashish for the reformatting. I will go ahead and merge this. Many thanks.

**Comment by dhakalaashish** [comment]
Thank you @nathzi1505 . Have a great day.

**Pull request merged**
