### PR TITLE
feat: Interpolate func updated

### LINKED ISSUE #26133: interpolate

### PR DESCRIPTION
**Pull request by Sanjay8602**
# PR Description

## Related Issue

Closes #26133 

## Checklist

- [x] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### CODE REVIEW

**Comment by Sanjay8602** [comment]
Hey @Ishticode please review this PR

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi @Sanjay8602 
Thanks for the PR. 
Could you briefly explain what this PR is meant to fix or add?
The changes currently made here has the test_interpolate for paddle failing as may be seen in the logs at https://github.com/unifyai/ivy/actions/runs/8178817582/job/22363875444?pr=28464
Let me know if something is unclear. Thanks :)

**Comment by Sanjay8602** [comment]
> Hi @Sanjay8602 Thanks for the PR. Could you briefly explain what this PR is meant to fix or add? The changes currently made here has the test_interpolate for paddle failing as may be seen in the logs at https://github.com/unifyai/ivy/actions/runs/8178817582/job/22363875444?pr=28464 Let me know if something is unclear. Thanks :)

In this issue the interpolate function was created but it needed the updation so I just deleted the exception and added 4-5 lines.
But I am getting 2-3 error in checks ex: check 8 and 9 where I am getting error but I am not able undrstand it plz help...

**Comment by Sanjay8602** [comment]
> Hi @Sanjay8602 Thanks for the PR. Could you briefly explain what this PR is meant to fix or add? The changes currently made here has the test_interpolate for paddle failing as may be seen in the logs at https://github.com/unifyai/ivy/actions/runs/8178817582/job/22363875444?pr=28464 Let me know if something is unclear. Thanks :)

test function is already created for this in test_layers file

**Comment by Ishticode** [comment]
Hi @Sanjay8602 
Which exception did you remove? Currently i don't see any under changes. 
And yes the test is already there but it has started to fail with changes on the PR. We would need to ensure it passes to continure. Please check details at our [Contributing Page](https://unify.ai/docs/ivy/overview/contributing.html)

**Pull request closed without merging**
