### PR TITLE
simplify requirements.txt

### PR DESCRIPTION
**Pull request by Sam-Armstrong**
Remove unnecessary dependencies from the requirements.txt file.

### CODE REVIEW

**Comment by Sam-Armstrong** [comment]
@hmahmood24 @YushaArif99 am I ok to merge this? seems to be fine with local testing, but I think the only way to test it out properly will be as part of the 'full ivy test from fresh dev perspective' which we can do soon.

**Review by YushaArif99 — APPROVED** [review]
lgtm at a first glance! But i guess we'll need to do some e2e testing to verify everything works smoothly from an end user's perspective.

**Review by hmahmood24 — CHANGES_REQUESTED** [review]
@Sam-Armstrong Thanks for working on this. The first question/observation that comes to mind is that `requirements.txt` is supposed to represent the minimal requirements in order to use `ivy` out of the box without minimal effort and since we are launching `ivy` with the purpose of using it as a transpiler with support for going from `torch` to `tensorflow`, do you think it makes sense to have these deps in the regular `requirements.txt` file because if someone does `pip install ivy`, we'd only install `numpy` and that's no good (it was good when it was to be used as a framework but is useless if we are marketing `ivy` as a transpiler with no support for transpiling to/fro `numpy` at launch). If you look at [transformers](https://github.com/huggingface/transformers/blob/3476c19e91a882fab8c76970a8798890a3f0f299/setup.py#L97) for example, they have `tensorflow`, `torch`, `jax` and `numpy` all listed down directly in their `setup.py` rather than have `optional` requirements files that the users themselves have to install regardless of whether [they're installing from source or from pip](https://ivy.dev/docs/overview/get_started.html#installing-using-pip)

**Comment by hmahmood24** [comment]
Also would be good to pin the versions as part of this PR @Sam-Armstrong

**Comment by Sam-Armstrong** [comment]
I'll make a new PR for pinning the frameworks, so we can check we agree on the pinned versions.

**Pull request merged**
