### PR TITLE
feat: Add elementwise experimental function

### LINKED ISSUE #25708: Elementwise function #amin
#amin elementwise function

### PR DESCRIPTION
**Pull request by portfolio-1**
# PR Description
closes #25708 
function experimental elementwise #amin

## Related Issue
#25785

Close #

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by a0m0rajab** [comment]
Hi @portfolio-1 thank you for your first contribution, can you follow the title requirement and link this PR to an issue?

when that's done, the compliance bot will show a passed message!

**Comment by portfolio-1** [comment]
> Congrats on making your first Pull Request and thanks for supporting Ivy! 🎉 Join the conversation in our [Discord](https://discord.com/invite/sXyFF8tDtm)
> 
> Here are some notes to understand our tests:
> 
> * We have merged all the tests in one file called `display_test_results` job. 👀 It contains the following two sections:
>   
>   * **Combined Test Results:** This shows the results of all the ivy tests that ran on the PR. ✔️
>   * **New Failures Introduced:** This lists the tests that fails on this PR.
> 
> Please make sure they are passing. 💪
> 
> Keep in mind that we will assign an engineer for this task and they will look at it based on the workload that they have, kindly be patient 😄.

thank you very much , i need to see the tests.

**Comment by portfolio-1** [comment]
> @portfolio-1 thanks for updating the title. Could you update the PR description as well to add the related issue: image
> 
> As for the tests, when the CI finishes it work, you can read it from the details: image
> 
> otherwise, you can just test it locally and post the test results here.

will you please help me to link the issue , i cannot find where is it ?

**Review by portfolio-1 — COMMENTED** [review]
please check the test case

**Comment by aparajith21** [comment]
Please edit PR description and comment Close #Issuenumber so that the issue gets linked appropriately and can then review

**Comment by Sam-Armstrong** [comment]
Closing as `amin` has already been added to the ivy functional api and backends.

**Pull request closed without merging**
