### PR TITLE
I added structural similarity index (SSIM) loss.

### PR DESCRIPTION
**Pull request by hi-sushanta**
Hi Ivy, I added a loss function for working on the structural similarity index (SSIM) loss calculation. It's a most popular loss in computer vision tasks.

And that is what my code looks like:
Screenshot from 2023-10-26 21-06-18

## Checklist

- [x] Did you add a function?
- [ ] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### Socials
https://twitter.com/hi_sushanta_

### CODE REVIEW

**Comment by hi-sushanta** [comment]
Has anyone seen my code?

**Comment by hi-sushanta** [comment]
Does this project have maintainers to review contributor changes?

**Comment by hi-sushanta** [comment]
Hi 👋

**Review by Ishticode — CHANGES_REQUESTED** [review]
Hi. Thanks for the PR and sorry for delays on our end.
Could you please add a test as any new function should have an accompanying test. Let me know if something is unclear. Thanks a lot for your patience. :)

**Comment by hi-sushanta** [comment]
Ok fine, I write testing code also.

**Review by Sam-Armstrong — APPROVED** [review]
Thanks for the contribution, apologies this took so long to review! I've made some fixes, will merge now.

**Pull request merged**
