### PR TITLE
Fix Ivy Failing Test: jax - activations.gelu

### LINKED ISSUE #28154: Fix Ivy Failing Test: jax - activations.gelu

### LINKED ISSUE #28160: Fix Ivy Failing Test: torch - activations.gelu

### PR DESCRIPTION
**Pull request by MuhammadNizamani**
# PR Description
All test are passing locally
gelu

## Related Issue

Closes #28160
Closes  #28154
## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Comment by Sarvesh-Kesharwani** [comment]
Hi @MuhammadNizamani,
test is failing for one of the backends
here is the decorator you can use to reproduce the failure 
@reproduce_failure('6.97.1', b'AXicY2QAAsYDDxhggBFK58BFADLuAhA=')
Thanks
image
image

**Comment by MuhammadNizamani** [comment]
@Sarvesh-Kesharwani  I will look into it Thanks for review

**Comment by samthakur587** [comment]
Hii @MuhammadNizamani the changes you made also not good float16 dtype the tol value you kept  more then 1e-2 it's not making any sense here.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by MuhammadNizamani** [comment]
i am working on it

**Pull request closed without merging**
