### PR TITLE
feat(paddle): Add kron method to Paddle Frontend

### LINKED ISSUE #26005: kron

### PR DESCRIPTION
**Pull request by Boghdady9**
# PR Description

Add kron method to Paddle Frontend and tested it
## Related Issue

Close #26005

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### CODE REVIEW

**Review by illia-bab — CHANGES_REQUESTED** [review]
Hey @Boghdady9 , thanks for contributing! I've tested your implementation locally. All the tests are passing except for `tensorflow` backend. Adding a falsifying example for you:
```
>       raise cls(fn.__name__, str(e), include_backend=True)
E       ivy.utils.exceptions.IvyBackendException: tensorflow: kron: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Broadcast between [2,1,2,1,2,1] and [1,2,1,2,1,2] is not supported yet. [Op:Mul]
E       Falsifying example: test_paddle_tensor_kron(
E           frontend='paddle',
E           on_device='cpu',
E           backend_fw='tensorflow',
E           dtype_and_x=(['int64', 'int64'], [array([[[0, 0],
E                     [0, 0]],
E             
E                    [[0, 0],
E                     [0, 0]]], dtype=int64), array([[[0, 0],
E                     [0, 0]],
E             
E                    [[0, 0],
E                     [0, 0]]], dtype=int64)]),
E           frontend_method_data=FrontendMethodData(ivy_init_module='ivy.functional.frontends.paddle', framework_init_module='paddle', init_name='to_tensor', method_name='kron'),
E           method_flags=FrontendMethodTestFlags(
E               num_positional_args=0,
E               as_variable=[False],
E               native_arrays=[False],
E               precision_mode=False,
E               inplace=False,
E               test_trace=False,
E               generate_frontend_arrays=False,
E           ),
E           init_flags=FrontendInitTestFlags(
E               num_positional_args=1,
E               as_variable=[False],
E               native_arrays=[False],
E           ),
E       )
```
Could you also tell me why `float16` dtype wasn't added to `with_supported_dtypes` decorator? According to `paddle` documentation, it's supported. Referrence - https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/kron_en.html.
Thanks and good luck!

**Comment by Boghdady9** [comment]
@illia-bab 

image

**Comment by Boghdady9** [comment]
@nathzi1505 
Hello

**Review by illia-bab — CHANGES_REQUESTED** [review]
Hey @Boghdady9 , your PR doesn't pass linting check, so please solve this and re-request review from me when you're done.
Apart from this, the falsifying example I outlined earlier pops up when I configure `pytest` to generate more test cases. But the problem seems to be related to `tensorflow` backend implementation rather than your work.
So when you fix the linting error, we're ready to merge!
Thanks and good luck!

**Pull request closed without merging**
