### PR TITLE
exists

### PR DESCRIPTION
**Pull request by davidlee1102**

### CODE REVIEW

**Comment by RashulChutani** [comment]
Hi @davidlee1102, Please add proper docstrings as per instructions here https://lets-unify.ai/ivy/contributing.html

**Review by RashulChutani — CHANGES_REQUESTED** [review]
Hi @davidlee1102, Please add proper docstrings as per instructions here https://lets-unify.ai/ivy/contributing.html

**Comment by davidlee1102** [comment]
Hi @RashulChutani ,
Let check again, I have done some function not available for this ivy, I mean
```
        >>> x = ivy.Container(a=None,\
                            b=ivy.native_array([[-1, 0, 0], [1, 0, 1], [1, 1, 1]]))
        >>> y = x.exists()
        >>> print(y)
        True
```

**Comment by davidlee1102** [comment]
Hi @RashulChutani,
Could you please check my code again
Thank you
David

**Comment by davidlee1102** [comment]
Hi @RashulChutani ,
Please check on `test-docstrings / run-docstring-tests`, I have added the output of when I was running ivy for checking result, for example:
```
    x = ivy.Container(a=ivy.native_array([[-1, 0, 1], [-1, 0, 1], [1, 0, -1]]), \
                      b=ivy.native_array([[-1, 0, 0], [1, 0, 1], [1, 1, 1]]))
    y = ivy.exists(x)
    print(y)
>>> True
```
When I was checking `test-docstrings / run-docstring-tests`, it was shown {a:true,b:true};
What wrong with it, can you tell me for fixing this problem?
Thank you,
David

**Comment by RashulChutani** [comment]
Hi @davidlee1102, Good Effort! Can you make sure to pass the docstrings tests for the exists function? Thanks.

**Review by RashulChutani — COMMENTED** [review]
Hi @davidlee1102, Good Effort! Can you make sure to pass the docstrings tests for the exists function? Thanks.

**Pull request closed without merging**
