### PR TITLE
Fix matrix_and_vector_products.test_numpy_matmul

### LINKED ISSUE #8110: Fix matrix_and_vector_products.test_numpy_matmul
|   |   |
|---|---|
|numpy|<a href="https://github.com/unifyai/ivy/actions/runs/6406936883"></a>
|jax|<a href="https://github.com/unifyai/ivy/actions/runs/6406936883"></a>
|tensorflow|<a href="https://github.com/unifyai/ivy/actions/runs/6406936883"></a>
|torch|<a href="https://github.com/unifyai/ivy/actions/runs/6406936883"></a>
|paddle|<a href="https://github.com/unifyai/ivy/actions/runs/6406936883"></a>

### PR DESCRIPTION
**Pull request by ananaphasia**
Close #8110

### CODE REVIEW

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ananaphasia** [comment]
waiting for review.

**Comment by ivy-seed** [comment]
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

**Comment by ananaphasia** [comment]
waiting for review.

**Comment by hirwa-nshuti** [comment]
Hey @ananaphasia 

Thanks for the PR😊
This issue has been fixed in this [commit](https://github.com/unifyai/ivy/commit/3da54bf207bba5bdea68a253fe6830df1afc8b0c) so I am going to close this item

**Pull request closed without merging**
